services:
  web: 
    build:
      context: app
      target: builder
    ports: 
      - '8000:8000'

  db:
    postgres:
      container_name: postgres
      image: postgres:latest
      environment:
        - POSTGRES_USER= admin_user
        - POSTGRES_PASSWORD= admin_321
        - POSTGRES_DB= sd_foodbank_db
      ports:
        - "5432:5432"
      restart: always

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4:latest
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
      ports:
        - "5050:80"
      restart: always