# Generated by Django 5.1.5 on 2025-02-19 21:31

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("transcript", models.JSONField(default=list)),
                ("audio", models.FileField(upload_to="conversations/")),
                ("time_started", models.DateTimeField(auto_now_add=True)),
                ("time_ended", models.DateTimeField()),
                ("length_of_call", models.DurationField()),
                ("strikes", models.PositiveIntegerField(default=0)),
                ("intent", models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name="admin",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
