# Generated by Django 5.1.5 on 2025-02-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_log_alter_admin_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="intent",
            new_name="intents",
        ),
    ]
