# Generated by Django 5.1.3 on 2024-11-14 00:25

from django.db import migrations
from admin_panel.models import Admin
from django.contrib.auth.hashers import make_password

def create_base_users(apps, schema_editor):
    """Creates base admin user in the Admin table"""

    Admin.objects.create(
        username='foodbank',
        email='foodbank@sandiego.edu',
        password=make_password('fb_123'), 
        is_staff=True,  
        is_superuser=True, 
    )

class Migration(migrations.Migration):
    
    dependencies = [
        ('admin_panel', '0002_rename_content_comment_contents_and_more'),
    ]

    operations = [
        migrations.RunPython(create_base_users)
    ]
