# Generated by Django 5.1.5 on 2025-03-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_rename_intent_log_intents"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.IntegerField()),
                ("appointmentID", models.IntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.TextField()),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
