# Generated by Django 5.1.5 on 2025-03-07 01:42

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_rename_intent_log_intents"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="time_ended",
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
