# Generated by Django 5.1.5 on 2025-03-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_log_time_ended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
