# Generated by Django 4.2.16 on 2025-03-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_appointmenttable'),
        ('admin_panel', '0004_user'),
    ]

    operations = [
    ]
