# Generated by Django 5.1.5 on 2025-03-06 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_appointmenttable"),
        ("admin_panel", "0004_user"),
    ]

    operations = []
