# Generated by Django 5.1.5 on 2025-03-07 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_merge_0004_appointmenttable_0004_user"),
        ("admin_panel", "0006_alter_log_length_of_call"),
    ]

    operations = []
