# Generated by Django 5.1.5 on 2025-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0007_merge_20250306_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=16),
        ),
    ]
