# Generated by Django 5.1.5 on 2025-03-19 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmenttable",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.user",
                null=True,  # Temporarily allow NULL values to prevent issues with existing rows
            ),
        ),
    ]
