# Generated by Django 5.1.5 on 2025-03-19 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0009_add_user_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmenttable",
            name="appointmentID",
        ),
        migrations.RemoveField(
            model_name="appointmenttable",
            name="userID",
        ),
        migrations.AlterField(
            model_name="appointmenttable",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.user",
            ),
        ),
    ]
