# Generated by Django 4.2.16 on 2025-04-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='approved_for_admin_panel',
            field=models.BooleanField(default=False, verbose_name='approved for admin panel'),
        ),
        migrations.AddField(
            model_name='admin',
            name='foodbank_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='foodbank emil'),
        ),
        migrations.AddField(
            model_name='admin',
            name='foodbank_id',
            field=models.CharField(default='unknown', max_length=50, verbose_name='foodbank employee ID'),
        ),
    ]
