# Generated by Django 5.1.5 on 2025-04-07 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0012_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmenttable",
            name="date",
        ),
        migrations.AlterField(
            model_name="log",
            name="time_ended",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
