# Generated by Django 4.2.16 on 2025-04-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_admin_foodbank_email'),
        ('admin_panel', '0014_appointmenttable_date'),
    ]

    operations = [
    ]
