# Generated by Django 5.1.5 on 2025-04-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0016_alter_admin_approved_for_admin_panel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(default="en", max_length=5),
        ),
    ]
