# Generated by Django 5.1.5 on 2025-05-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0017_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="foodbank_id",
            field=models.CharField(
                default="", max_length=50, verbose_name="foodbank employee ID"
            ),
        ),
    ]
