# Generated by Django 5.1.5 on 2025-05-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0018_alter_admin_foodbank_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={
                "permissions": [
                    (
                        "can_approve_users",
                        "Can approve users to access the admin panel.",
                    )
                ]
            },
        ),
    ]
