# Generated by Django 4.2.16 on 2025-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_alter_admin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text='Caller language preference', max_length=2),
        ),
    ]
