# Generated by Django 4.2.16 on 2025-05-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_log_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es-MX', 'Spanish')], default='en', help_text='Caller language preference', max_length=5),
        ),
    ]
