# Generated by Django 5.1.5 on 2025-05-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0021_alter_log_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="total_strikes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
