# Generated by Django 5.1.5 on 2025-05-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0021_alter_log_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="forwarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="log",
            name="forwarded_reason",
            field=models.CharField(
                blank=True,
                choices=[("user", "User Requested"), ("auto", "Automatic")],
                max_length=10,
                null=True,
            ),
        ),
    ]
