# Generated by Django 5.1.5 on 2025-05-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0022_log_forwarded_log_forwarded_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="forwarded_reason",
            field=models.CharField(
                blank=True,
                choices=[("caller", "Caller Requested"), ("auto", "Automatic")],
                max_length=10,
                null=True,
            ),
        ),
    ]
