# Generated by Django 5.1.5 on 2025-05-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0022_log_total_strikes"),
        ("admin_panel", "0023_alter_log_forwarded_reason"),
    ]

    operations = []
